/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using Telerik.OpenAccess.Metadata;
using Telerik.Sitefinity.Data;
using Telerik.Sitefinity.Model;

namespace Test
{
    public class OpenAccessTestModuleProvider : TestModuleDataProvider, IOpenAccessDataProvider
    {
        public OpenAccessProviderContext Context
        {
            get;
            set;
        }

        public MetadataSource GetMetaDataSource(IDatabaseMappingContext context)
        {
            return null;
        }
    }
}