/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using Telerik.Sitefinity.Web.UI.ContentUI;

namespace Test
{
    internal class TestModuleView : ContentView
    {

    }
}