/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using Telerik.Sitefinity.Localization;

namespace Test
{
    internal class TestModuleResources : Resource
    {
        [ResourceEntry(
            "PageGroupNodeTitle",
            Value = "Test Group",
            Description = "",
            LastModified = "")
        ]
        public string PageGroupNodeTitle
        {
            get { return this["PageGroupNodeTitle"]; }
        }

        [ResourceEntry(
            "PageGroupNodeDescription",
            Value = "Test Group Description",
            Description = "",
            LastModified = "")
        ]
        public string PageGroupNodeDescription
        {
            get { return this["PageGroupNodeDescription"]; }
        }

        [ResourceEntry(
            "ModuleTitle",
            Value = "Test",
            Description = "",
            LastModified = "")
        ]
        public string ModuleTitle
        {
            get { return this["ModuleTitle"]; }
        }

        [ResourceEntry(
            "ModuleDescription",
            Value = "Test Description",
            Description = "",
            LastModified = "")
        ]
        public string ModuleDescription
        {
            get { return this["ModuleDescription"]; }
        }

        [ResourceEntry(
            "ModuleViewTitle",
            Value = "Test View",
            Description = "",
            LastModified = "")
        ]
        public string ModuleViewTitle
        {
            get { return this["ModuleViewTitle"]; }
        }

        [ResourceEntry(
            "ModuleViewDescription",
            Value = "Test View Frontend Control",
            Description = "",
            LastModified = "")
        ]
        public string ModuleViewDescription
        {
            get { return this["ModuleViewDescription"]; }
        }
    }
}