/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using Telerik.Sitefinity;
using Telerik.Sitefinity.Configuration;
using Telerik.Sitefinity.Fluent.Definitions;
using Telerik.Sitefinity.Web.UI.ContentUI.Config;

namespace Test
{
    internal static class TestModuleDefinition
    {
        internal static ContentViewControlElement DefineTestBackendContentView(ConfigElement parent)
        {
            // define content view control
            var fluentContentView = App.WorkWith().Module(TestModule.moduleName).DefineContainer(parent, BackendDefinitionName, typeof(TestModuleItem));
            var backendContentView = fluentContentView.Get();

            backendContentView.ViewsConfig.AddLazy(TestModuleDefinition.BackendListViewName, () => DefineNewsBackendListView(fluentContentView));
            return backendContentView;
        }

        private static ConfigElement DefineNewsBackendListView(ContentViewControlDefinitionFacade fluentContentView)
        {
            var fluentMasterView = fluentContentView
                .AddMasterView(TestModuleDefinition.BackendListViewName)
                .LocalizeUsing<TestModuleResources>()
                .SetTitle("Test")
                .SetServiceBaseUrl("~/Sitefinity/Services/Content/TestItemService.svc/");
            var newsGridView = fluentMasterView.Get();
            return newsGridView;
        }

        public const string BackendDefinitionName = "TestModuleBackend";
        public const string BackendListViewName = "TestModuleBackendList";
    }
}