/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using System;
using Telerik.Sitefinity;
using Telerik.Sitefinity.Workflow.Model.Tracking;

namespace Test
{
    internal class TestModuleItem : IWorkflowItem
    {
        public Guid Id
        {
            get { throw new NotImplementedException(); }
        }

        public ApprovalTrackingRecordMap ApprovalTrackingRecordMap
        {
            get
            {
                throw new NotImplementedException();
            }
            set
            {
                throw new NotImplementedException();
            }
        }
    }
}