/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using System;
using Telerik.Sitefinity.Data;

namespace Test
{
    public class TestModuleDataProvider : DataProviderBase
    {
        public override Type[] GetKnownTypes()
        {
            return new Type[] { typeof(TestModuleItem) };
        }

        public override string RootKey
        {
            get { return "TestModule"; }
        }
    }
}