/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using Telerik.Sitefinity.Configuration;
using Telerik.Sitefinity.Data;

namespace Test
{
    public class TestModuleManager : ManagerBase<TestModuleDataProvider>
    {
        public TestModuleManager()
            : this(null)
        {
        }

        public TestModuleManager(string providerName)
            : base(providerName)
        {
        }

        public TestModuleManager(string providerName, string transactionName)
            : base(providerName, transactionName)
        {
        }

        protected override GetDefaultProvider DefaultProviderDelegate
        {
            get { return () => Config.Get<TestModuleConfig>().DefaultProvider; }
        }

        public override string ModuleName
        {
            get { return TestModule.moduleName; }
        }

        protected override ConfigElementDictionary<string, DataProviderSettings> ProvidersSettings
        {
            get { return Config.Get<TestModuleConfig>().Providers; }
        }

        public static TestModuleManager GetManager()
        {
            return ManagerBase<TestModuleDataProvider>.GetManager<TestModuleManager>();
        }

        public static TestModuleManager GetManager(string providerName, string transactionName)
        {
            return ManagerBase<TestModuleDataProvider>.GetManager<TestModuleManager>(providerName, transactionName);
        }

        public static TestModuleManager GetManager(string providerName)
        {
            return ManagerBase<TestModuleDataProvider>.GetManager<TestModuleManager>(providerName);
        }
    }
}