/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.0.0.7
</auto-generated>
------------------------------------------------------------------------------ */

using System;
using System.Text.RegularExpressions;
using Telerik.Sitefinity;
using Telerik.Sitefinity.Abstractions;
using Telerik.Sitefinity.Configuration;
using Telerik.Sitefinity.Fluent.Modules;
using Telerik.Sitefinity.Services;

namespace Test
{
    public class TestModule : ModuleBase
    {
        public override Guid LandingPageId
        {
            get { return homePageId; }
        }

        public override void Initialize(ModuleSettings settings)
        {
            base.Initialize(settings);

            App.WorkWith().Module(Name)
                .Initialize()
                    .Configuration<TestModuleConfig>()
                    .Localization<TestModuleResources>();
        }

        public override void Install(SiteInitializer initializer)
        {
			var urlName = Regex.Replace(moduleName, @"[\-\!\$\(\)\=\@\d_\']+", "-", RegexOptions.IgnoreCase).ToLower();
            initializer.Installer
                .CreateModuleGroupPage(groupPageId, moduleName)
                    .PlaceUnder(CommonNode.TypesOfContent)
                    .LocalizeUsing<TestModuleResources>()
                    .SetTitleLocalized("PageGroupNodeTitle")
                    .SetUrlName(urlName)
                    .SetDescriptionLocalized("PageGroupNodeDescription")
                    .AddChildPage(TestModule.homePageId, "Home")
                        .LocalizeUsing<TestModuleResources>()
                        .SetTitleLocalized("ModuleTitle")
                        .SetHtmlTitleLocalized("ModuleTitle")
                        .SetUrlName(urlName + "-home")
                        .SetDescriptionLocalized("ModuleDescription")
                        .AddContentView(TestModuleDefinition.BackendDefinitionName, "TestBackendView")
                        .Done()
                    .Done()
            .PageToolbox()
                .ContentSection()
                    .LoadOrAddWidget<TestModuleView>("ModuleViewTitle")
                        .LocalizeUsing<TestModuleResources>()
                        .SetTitle("ModuleViewTitle")
                        .SetDescription("ModuleViewDescription")
                        .SetCssClass("sfTestViewIcn")
                        .Done()
                    .Done()
                .Done()
            .AddWorkflowType<TestModuleItem>()
                .SetTitle(moduleName)
                .SetServiceUrl("~/Workflows/TestWorkflow.xamlx")
                .LocalizeUsing<TestModuleResources>()
                .Done();

        }

        public override void Upgrade(SiteInitializer initializer, Version upgradeFrom)
        {
        }

        protected override ConfigSection GetModuleConfig()
        {
            return Config.Get<TestModuleConfig>();
        }

        public override Type[] Managers
        {
            get { return new Type[] { typeof(TestModuleManager) }; }
        }

        internal static Guid groupPageId = new Guid("AB45CA65-B763-4C8A-84F1-442F701D3971");
        internal static Guid homePageId = new Guid("AB45CA65-B763-4C8A-84F1-442F701D3972");
        internal const string moduleName = "Test";
    }
}