<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="Telerik.Sitefinity, Version=14.4.8000.0, Culture=neutral, PublicKeyToken=b28c218413bcebee, processorArchitecture=MSIL">
      <HintPath>packages\Telerik.Sitefinity.All.14.4.8000\lib\net40\Telerik.Sitefinity.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="BeforeBuild">
 
  </Target>
</Project>
